name: Auto label

on: pull_request_review

env:
  IS_FORK: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
  IS_DEPENDABOT: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}

jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - name: Label when approved
        if: ${{ env.IS_FORK == 'false' && env.IS_DEPENDABOT == 'false' }}
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: '2'
          ADD_LABEL: 'ready to merge'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
