name: E2E tests

on:
  pull_request:

env:
  CACHE_DIST_KEY: dist-${{ github.head_ref }}-${{ github.ref }}-${{ github.sha }}
  BASE_REF_DEMO: dist/demo/browser/${{ github.base_ref }}
  LOCAL_REF_DEMO: dist/demo/browser
  NX_BRANCH: ${{ github.event.number }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NG_SERVER_PORT: 3333

jobs:
  build-demo:
    if: ${{ !contains(github.head_ref , 'release/') }}
    name: Build demo # for reuse in e2e jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Try rebase locally for check affected e2e
        uses: ./.github/actions/rebase

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Mark demo-app directory for persist in cache
        uses: actions/cache@v3
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

      - name: Building demo-app of git-branch without cache
        run: npx nx build --skip-nx-cache -c next --output-path dist/demo/browser

  cypress:
    if: ${{ !contains(github.head_ref , 'release/') }}
    needs: [build-demo]
    runs-on: ubuntu-latest
    services:
      sorry-cypress-director:
        image: agoldis/sorry-cypress-director:2.4.4
        ports:
          - 1234:1234
    strategy:
      fail-fast: false
      matrix:
        project:
          [
            addon-doc,
            addon-charts,
            addon-commerce,
            addon-editor,
            addon-icons,
            addon-mobile,
            addon-preview,
            addon-table,
            addon-tablebars,
            core,
            deep,
            demo,
            kit,
          ]
        type: [desktop]
        include:
          - project: kit
            type: mobile
    name: ${{ matrix.project }} / ${{ matrix.type }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Setup Cypress and Sorry Cypress
        uses: ./.github/actions/cypress
        with:
          cypress-api-url: http://localhost:1234/
          snapshot-path: ./projects/demo-integrations/cypress/snapshots

      - name: Download ${{ env.LOCAL_REF_DEMO }} for serve locally
        uses: actions/cache@v3
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

      - name: Serve ${{ env.LOCAL_REF_DEMO }} in background
        run: npx nx serve-compiled --path ${{ env.LOCAL_REF_DEMO }} --port ${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.LOCAL_REF_DEMO }}
        run: npx nx e2e-ci --key localhost --folder ${{ matrix.project }} --config cypress.config.${{ matrix.type }}.ts

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Download ${{ env.BASE_REF_DEMO }} for serve locally
        run: |
          git clone \
                --depth 1 \
                --branch snapshots/demo/next/${{ github.base_ref }} \
                https://github.com/Tinkoff/taiga-ui.git ${{ env.BASE_REF_DEMO }}

      - name: Serve ${{ env.BASE_REF_DEMO }} in background
        run: npx nx serve-compiled --path ${{ env.BASE_REF_DEMO }} --port ${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.BASE_REF_DEMO }}
        continue-on-error: true
        env: # note: need to collect all
          # diff files for lumberjack bot
          CYPRESS_failOnSnapshotDiff: 0
        run: npx nx e2e-ci --key next --folder ${{ matrix.project }} --config cypress.config.${{ matrix.type }}.ts

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Check if diff-output exists
        id: diff-checker
        run: |
          echo "diff_exist=$(find ${{ env.SNAPSHOTS_PATH }} -regex '.*\.diff\.png$' | wc -l | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT

      - name: Fall with an error if diff-output exists
        if: ${{ steps.diff-checker.outputs.diff_exist != '0' }}
        run: |
          find ${{ env.SNAPSHOTS_PATH }} -regex '.*\.diff\.png$' -exec echo "{}" \;
          exit 1

      - name: Update artifacts / ${{ env.SNAPSHOTS_KEY }}
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: ${{ env.SNAPSHOTS_PATH }}/**/*.diff.png
          name: ${{ env.SNAPSHOTS_KEY }}
          if-no-files-found: ignore
          retention-days: 1

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
