name: Publish Taiga UI packages

on:
  push:
    branches: ['release/*']

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Build publishable libraries
        run: npm run run-many:build:libs

      - name: Publish libraries
        run: npm run run-many:publish:libs

      - name: Get version
        id: info
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Announce
        uses: ./.github/actions/announce
        with:
          version: ${{ steps.info.outputs.version }}
          url: ${{ secrets.ANNOUNCE_WEBHOOK }}
          channel: ${{ secrets.ANNOUNCE_TARGET }}

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
