name: counter_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  counter_widgets:
    path: ../../packages/counter_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  counter_lints:
    path: ../../packages/counter_lints

flutter:
  uses-material-design: true
