name: Taiga-UI rebase
description: Taiga-UI rebase

runs:
  using: composite
  steps:
    - name: Try rebase locally for check affected
      uses: imba-tjd/rebase-upstream-action@0.5
      with:
        upstream: Tinkoff/taiga-ui
        branch: ${{ github.base_ref }}
        push: false
