name: Announce
description: Taiga-UI release announcement

inputs:
  url:
    description: Webhook url
    required: true
  version:
    description: Release version
    required: true
  channel:
    description: Channel
    required: true

runs:
  using: composite
  steps:
    - name: Announce
      shell: bash
      run: |
        curl --http1.1 -X POST -H "Content-Type: application/json" -d '{"text": "New version [v${{ inputs.version }}](https://github.com/Tinkoff/taiga-ui/releases/tag/v${{ inputs.version }}) released :tada:", "username": "Taiga release", "channel": "${{ inputs.channel }}"}' ${{ inputs.url }}
